tasks:
  - before: npm install -g @tendermint/starport@0.0.10 --save
  - init: npm install -g @tendermint/starport@0.0.10 --save
  - command: npm install -g @tendermint/starport@0.0.10 --save
  - command: starport serve --verbose
