tasks:
  - prebuild: npm install -g @tendermint/starport@0.0.10 --save
  - name: Install required dependency
    command: npm install -g @tendermint/starport@0.0.10 --save
  - name: Start starport
    command: starport serve --verbose


