version: 1
accounts:
  - name: user1
    coins: ["10000000000token", "100000000stake"]
  - name: user2
    coins: ["500000000000token"]
  - name: user3
    coins: ["10000000000token"]
  - name: realDoctor
    coins: ["1000000000000token"]
  - name: fakeDoctor
    coins: ["1000000token"]
validator:
  name: user1
  staked: "100000000stake"