version: 1
accounts:
  - name: user1
    coins: ["1000token", "100000000stake"]
  - name: user2
    coins: ["500token"]
  - name: doctor
    coins: ["100000token"]
validator:
  name: user1
  staked: "100000000stake"
